// <auto-generated />
using EFcoreOrderAssignmentDll;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFcoreOrderAssignmentDll.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20220620162050_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFcoreOrderAssignmentDll.Entities.CustomerMaster", b =>
                {
                    b.Property<string>("Customer_FName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Customer_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customer_Phone")
                        .HasColumnType("int");

                    b.HasKey("Customer_FName");

                    b.ToTable("CustomerMasters");
                });

            modelBuilder.Entity("EFcoreOrderAssignmentDll.Entities.ItemMaster", b =>
                {
                    b.Property<string>("Item_Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Item_Qty")
                        .HasColumnType("int");

                    b.Property<int>("Item_Rate")
                        .HasColumnType("int");

                    b.HasKey("Item_Name");

                    b.ToTable("ItemMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
